### PR TITLE
[Merged by Bors] - fix(bors.toml): use maximum timeout suppored by github actions

### PR DESCRIPTION
**Pull request by gebner**
I'm confident we'll be able to breach the four-hour barrier before we move to Lean 4.  Bigger, better, blazingly slow!

TO CONTRIBUTORS:

Make sure you have:

  * [ ] reviewed and applied the coding style: [coding](https://github.com/leanprover-community/mathlib/blob/master/docs/contribute/style.md), [naming](https://github.com/leanprover-community/mathlib/blob/master/docs/contribute/naming.md)
  * [ ] reviewed and applied [the documentation requirements](https://github.com/leanprover-community/mathlib/blob/master/docs/contribute/doc.md)
  * [ ] for tactics:
     * [ ] added or adapted documentation in the [tactic doc entries](https://github.com/leanprover-community/mathlib/blob/master/docs/contribute/doc.md#tactic-doc-entries)
     * [ ] write an example of use of the new feature in [test/tactics.lean](https://github.com/leanprover-community/mathlib/blob/master/test/tactics.lean) or another test file
  * [ ] make sure definitions and lemmas are put in the right files
  * [ ] make sure definitions and lemmas are not redundant

If this PR is related to a discussion on Zulip, please include a link in the discussion.

For reviewers: [code review check list](https://github.com/leanprover-community/mathlib/blob/master/docs/contribute/code-review.md)

### CODE REVIEW

**Comment by gebner** [comment]
It still says "waiting for review" on bors.  Let me make this clear:

bors r+

**Comment by bryangingechen** [comment]
It's hard to edit a 5-line file without causing a merge conflict...

**Comment by bryangingechen** [comment]
The last batch caused a crash?
```
{{:badmatch, {:error, :get_pr_commits, 401, 12}},
 [
   {BorsNG.Worker.Batcher,
    :"-start_waiting_merged_batch/4-fun-2-", 5,
    [file: 'lib/worker/batcher.ex', line: 394]},
   {Enum, :"-reduce/3-lists^foldl/2-0-", 3,
    [file: 'lib/enum.ex', line: 1940]},
   {BorsNG.Worker.Batcher, :start_waiting_merged_batch, 4,
    [file: 'lib/worker/batcher.ex', line: 389]},
   {BorsNG.Worker.Batcher, :start_waiting_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 356]},
   {BorsNG.Worker.Batcher, :poll_, 1,
    [file: 'lib/worker/batcher.ex', line: 256]},
   {BorsNG.Worker.Batcher, :handle_info, 2,
    [file: 'lib/worker/batcher.ex', line: 204]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]}
 ]}
```

**Comment by bryangingechen** [comment]
Going to try this again

bors r+

**Pull request closed without merging**
